let disposeDesk=()=>{};
import {projects,artworks,categories} from './data.js';
const main=document.querySelector('main');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const chips=items=>`<div class="chips">${items.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;
function card(p,i=0){return `<a class="project-card color-${i%3}" href="#/project/${esc(p.id)}"><div class="card-art"><span class="file-label">${esc(p.kind||p.category)}</span>${p.cover?`<img src="${esc(p.cover.src)}" alt="${esc(p.cover.alt)}">`:`<div class="type-art">${esc(p.title)}</div>`}<span class="card-arrow">↗</span></div><div class="card-copy"><span class="eyebrow">${esc(p.category)}</span><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p></div></a>`;}
const contactLinks=()=>`<div class="contact-links"><a href="https://www.linkedin.com/in/milana-smirnoff/" target="_blank" rel="noopener">LinkedIn ↗</a><a href="mailto:milashka.smirnoff@gmail.com">milashka.smirnoff@gmail.com ↗</a></div>`;
function skillsSection(){return `<section class="section skills" id="skills"><h2>My skills</h2><div class="detail-grid"><div><h3>Programming</h3>${chips(['C++','Java','Python','HTML','CSS'])}</div><div><h3>Engineering</h3>${chips(['SystemVerilog','Vivado','KiCad','Multisim','Arduino','LTspice','MATLAB','Linux','Git / GitHub'])}</div><div><h3>Art & 3D</h3>${chips(['Blender','Autodesk Maya','ZBrush','Unity','Onshape'])}</div></div></section>`;}
function experienceContent(){return `<div class="experience-grid"><section><span class="eyebrow">JUNE 2024 — AUGUST 2026</span><h3>Lockheed Martin</h3><ul><li>Software Engineering Intern · 2026</li><li>Systems Engineering Intern · 2025</li><li>Student Tech Intern · 2024–2025</li><li>Software testing, circuit design & documentation</li></ul></section><section><span class="eyebrow">RPI · CAMPUS INVOLVEMENT</span><h3>Leadership & outreach</h3><ul><li><strong>Women’s Mentoring Program:</strong> Student Mentor · 5 students</li><li><strong>Crafts Club:</strong> President · 40+ attendees per event</li><li><strong>RPI Admissions:</strong> Student Ambassador</li><li><strong>Girls Who Code:</strong> Outreach & Marketing Design Coordinator</li></ul></section></div>`;}
function laptopPortrait(){return `<div class="sketch-laptop" aria-label="Pink illustrated laptop with Milana’s portrait"><span class="laptop-spark spark-one" aria-hidden="true">✧</span><div class="sketch-screen"><div class="sketch-toolbar"><span>hello, i'm milana ♡</span><span aria-hidden="true">− □ ×</span></div><img src="./milana.png" alt="Milana Smirnoff"><div class="sketch-screen-bottom" aria-hidden="true">♡ <span>engineer + artist</span> ✧</div></div><div class="sketch-keyboard" aria-hidden="true"><div class="key-rows"></div><div class="trackpad"></div></div><span class="laptop-spark spark-two" aria-hidden="true">✳</span></div>`;}
function home(){main.innerHTML=`<section class="portfolio-hero section"><div class="hero-copy"><h1>Milana<br>Smirnoff<span aria-hidden="true">♡</span></h1><p class="role">Engineer & Artist</p><ul class="intro-list"><li>Computer & Systems Engineering + Electronic Arts</li><li>RPI · Class of 2029</li></ul><div class="hero-actions"><a class="button" href="./resume.pdf?v=20260924" target="_blank" rel="noopener">My résumé ↗</a><a class="button secondary" href="#/work">View projects →</a></div></div>${laptopPortrait()}</section>${skillsSection()}<section class="section home-experience" id="experience"><div class="section-heading"><h2>Experience</h2><a class="text-link" href="#/experience">View experience ↗</a></div>${experienceContent()}</section><section class="section" id="projects"><div class="section-heading"><h2>Projects</h2><a class="text-link" href="#/work">All projects ↗</a></div>${projectGroups()}</section><section class="section contact-section" id="contact"><h2>Let’s connect</h2>${contactLinks()}</section>`;}
function projectGroups(){return `<section class="project-group" id="engineering-projects"><h2>Engineering</h2><div class="cards">${projects.filter(p=>p.kind==='Engineering').map(card).join('')}</div></section><section class="project-group" id="art-projects"><h2>Art</h2><div class="cards">${[...projects.filter(p=>p.kind!=='Engineering'),...artworks].map(card).join('')}</div><p class="art-coming">3D modeling, digital & traditional artwork coming soon.</p></section>`;}
function work(){main.innerHTML=`<section class="section page"><h1>Projects</h1><nav class="project-jumps" aria-label="Project categories"><a href="#engineering-projects">Engineering ↓</a><a href="#art-projects">Art ↓</a></nav>${projectGroups()}</section>`;main.querySelectorAll('.project-jumps a').forEach(a=>a.onclick=e=>{e.preventDefault();main.querySelector(a.getAttribute('href')).scrollIntoView({behavior:'smooth'});});}
function art(){history.replaceState(null,'','#/work');work();}
const mediaStore=[];
function media(block){const id=mediaStore.push(block)-1,imgs=block.images||[];const image=(im,i)=>`<button class="image-button" data-open="${id}" data-index="${i}"><img src="${esc(im.src)}" alt="${esc(im.alt)}" loading="lazy"></button>`;if(block.type==='model')return `<section class="media"><h2>${esc(block.title||'Explore in 3D')}</h2><model-viewer src="${esc(block.src)}" ${block.poster?`poster="${esc(block.poster)}"`:''} alt="${esc(block.alt)}" camera-controls touch-action="pan-y"></model-viewer><a href="${esc(block.src)}" download>Download 3D model</a></section>`;if(block.type==='beforeAfter')return `<section class="media comparison"><h2>${esc(block.title||'Before & after')}</h2><div class="comparison-stage"><img src="${esc(block.before.src)}" alt="${esc(block.before.alt)}"><img class="after" src="${esc(block.after.src)}" alt="${esc(block.after.alt)}"></div><label>Before / after <input type="range" min="0" max="100" value="50" aria-label="Reveal after image"></label></section>`;if(!imgs.length)return '';return `<section class="media"><h2>${esc(block.title||'Gallery')}</h2>${block.type==='slideshow'||block.type==='thumbnails'?`<div class="slideshow" data-media="${id}"><div class="slide-image">${image(imgs[0],0)}</div><div class="slide-controls"><button data-step="-1" aria-label="Previous slide">←</button><p class="caption">${esc(imgs[0].caption)}</p><span class="counter">1 / ${imgs.length}</span><button data-step="1" aria-label="Next slide">→</button></div><div class="indicators">${imgs.map((im,i)=>`<button data-slide="${i}" aria-label="Show image ${i+1}" aria-current="${i===0}">${block.type==='thumbnails'?`<img src="${esc(im.src)}" alt="">`:'<span></span>'}</button>`).join('')}</div></div>`:`<div class="gallery ${block.type==='hero'?'single':''}">${imgs.map((im,i)=>`<figure>${image(im,i)}${im.caption?`<figcaption>${esc(im.caption)}</figcaption>`:''}</figure>`).join('')}</div>`}</section>`;}
function project(id){const p=[...projects,...artworks].find(p=>p.id===id);if(!p){main.innerHTML='<section class="page section"><h1>Project not found.</h1><a href="#/work">Back to projects</a></section>';return;}main.innerHTML=`<article class="page section project-page"><a class="text-link" href="#/work">← Back to projects</a><p class="eyebrow">${esc(p.category)} · ${esc(p.date)}</p><h1>${esc(p.title)}</h1>${chips([p.status,...p.tools].filter(Boolean))}<p class="lede">${esc(p.summary)}</p>${p.link?`<a class="button" href="${esc(p.link)}" target="_blank" rel="noopener">Visit website ↗</a>`:''}<div class="detail-grid">${(p.details||[]).map(([title,copy])=>`<section><h2>${esc(title)}</h2><ul><li>${esc(copy)}</li></ul></section>`).join('')}</div>${(p.media||[]).map(media).join('')}${p.albums?`<h2 class="album-title">Club photos</h2><div class="album-grid">${p.albums.map(a=>a.images.length?media({type:'slideshow',title:a.title,images:a.images}):`<section class="album"><span>▧</span><h3>${esc(a.title)}</h3><p>Photos coming soon.</p></section>`).join('')}</div>`:!p.media?.length?'<div class="image-note">Project images will be added as the work develops.</div>':''}</article>`;bindMedia();}
function about(){main.innerHTML=`<section class="page section about"><div><p class="eyebrow">ABOUT ME</p><h1>Milana Smirnoff</h1><p class="role">Engineer & Artist</p><ul class="about-list"><li>RPI · Class of 2029</li><li>Computer & Systems Engineering + Electronic Arts</li><li>Crafts Club President</li><li>Girls Who Code outreach & design</li><li>Snowboarding, tennis & ice hockey</li><li>Russian & American Sign Language (ASL)</li></ul><h2 class="connect-heading">Let’s connect</h2>${contactLinks()}</div>${laptopPortrait()}</section>${skillsSection()}`;}
function skills(){main.innerHTML=skillsSection();}
function contact(){main.innerHTML=`<section class="section page contact-section"><h1>Let’s connect</h1>${contactLinks()}</section>`;}
function experience(){main.innerHTML=`<section class="page section"><h1>Experience</h1>${experienceContent()}<a class="button" href="./resume.pdf?v=20260924" target="_blank" rel="noopener">Full résumé ↗</a></section>`;}
let lightImages=[],lightIndex=0,lastFocus;const dialog=document.querySelector('dialog');function updateLight(){const im=lightImages[lightIndex];dialog.querySelector('img').src=im.src;dialog.querySelector('img').alt=im.alt;dialog.querySelector('figcaption').textContent=im.caption||'';}function openLight(id,index){lightImages=mediaStore[id].images;lightIndex=index;lastFocus=document.activeElement;updateLight();dialog.showModal();}dialog.querySelector('.close').onclick=()=>dialog.close();dialog.onclose=()=>lastFocus?.focus();dialog.querySelector('.lbprev').onclick=()=>{lightIndex=(lightIndex-1+lightImages.length)%lightImages.length;updateLight();};dialog.querySelector('.lbnext').onclick=()=>{lightIndex=(lightIndex+1)%lightImages.length;updateLight();};dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')dialog.querySelector('.lbprev').click();if(e.key==='ArrowRight')dialog.querySelector('.lbnext').click();});main.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openLight(+b.dataset.open,+b.dataset.index);});
function bindMedia(){document.querySelectorAll('.slideshow').forEach(el=>{let n=0,start;const id=+el.dataset.media,imgs=mediaStore[id].images;const set=i=>{n=(i+imgs.length)%imgs.length;const b=el.querySelector('[data-open]'),im=imgs[n];b.dataset.index=n;b.querySelector('img').src=im.src;b.querySelector('img').alt=im.alt;el.querySelector('.caption').textContent=im.caption||'';el.querySelector('.counter').textContent=`${n+1} / ${imgs.length}`;el.querySelectorAll('[data-slide]').forEach(b=>b.setAttribute('aria-current',String(+b.dataset.slide===n)));};el.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>set(n+ +b.dataset.step));el.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>set(+b.dataset.slide));el.addEventListener('touchstart',e=>start=e.touches[0].clientX,{passive:true});el.addEventListener('touchend',e=>{const d=start-e.changedTouches[0].clientX;if(Math.abs(d)>45)set(n+(d>0?1:-1));},{passive:true});});document.querySelectorAll('.comparison input').forEach(r=>r.oninput=()=>r.closest('.comparison').style.setProperty('--reveal',r.value+'%'));if(document.querySelector('model-viewer')&&!document.querySelector('#model-script')){const s=document.createElement('script');s.id='model-script';s.type='module';s.src='https://ajax.googleapis.com/ajax/libs/model-viewer/4.0.0/model-viewer.min.js';document.head.append(s);}}
function route(){disposeDesk();disposeDesk=()=>{};mediaStore.length=0;const path=location.hash.slice(2).split('/');if(path[0]==='project')project(path[1]);else ({work,art,about,experience,skills,contact}[path[0]]||home)();document.querySelectorAll('nav a').forEach(a=>a.setAttribute('aria-current',a.hash===location.hash?'page':'false'));document.title=`${path[0]?({work:'Projects',art:'Projects'}[path[0]]||path[0].charAt(0).toUpperCase()+path[0].slice(1))+' | ':''}Milana Smirnoff`;window.scrollTo(0,0);}window.addEventListener('hashchange',()=>{route();main.focus({preventScroll:true});});route();

