// Add your original images to assets/projects/. Each project chooses its own media blocks.
// Image: { src, alt, caption? }. Blocks: hero, slideshow, gallery, process,
// thumbnails, beforeAfter ({before,after}), model ({src,poster,alt}).
export const categories=['3D Modeling','Digital Art','Traditional Art','Graphic / Visual Design','Creative Coding','Crafts / Making'];
export const projects=[
 {id:'fpga-circuits',title:'FPGA Digital Logic',kind:'Engineering',category:'Digital circuits',date:'August 2026 — present',status:'RPI coursework',summary:'SystemVerilog circuits & simulation testbenches',description:'Computer Components & Operations coursework at RPI.',tools:['SystemVerilog','Vivado','FPGA'],details:[['Circuit design','Design and implement FPGA circuits.'],['Verification','Develop testbenches to simulate, verify, and debug digital logic.']],media:[]},
 {id:'fairy-runner',title:'Fairy Runner',kind:'Engineering',category:'Creative Coding',date:'May 2026 — present',status:'In progress',summary:'Arduino touchscreen platform game · In progress',description:'I’m developing a custom device with a fairy-themed platform game, using Arduino and a touchscreen display. The project brings together embedded software, graphics, user input, and audio feedback.',tools:['Arduino','Embedded software','Touchscreen'],details:[['The game','Developing game mechanics, graphics, touch input, and audio feedback.'],['The enclosure','Designing a pink, custom phone-inspired enclosure.'],['What’s next','Planning a future standalone version with a custom PCB.']],media:[]},
 {id:'crafts-club',title:'RPI Crafts Club',kind:'Community',category:'Crafts / Making',date:'April 2026 — present',status:'President',summary:'Club leadership, events & website',description:'As president, I reorganized and grew RPI Crafts Club, establishing weekly meetings with more than 40 attendees per event. I plan creative events and coordinate campus funding, outreach, and collaborations.',tools:['Event planning','Web design','Creative leadership'],details:[['40+ makers','Weekly meetings with more than 40 attendees per event.'],['Room to grow','Secured a $500 donation and submitted a Union funding proposal to expand programming and supplies.'],['A digital home','Developed and maintain the club website and digital resources.']],link:'https://rpicraftsclub.github.io/links/',media:[],albums:[{title:'Meetings & events',images:[]},{title:'Projects & making',images:[]},{title:'Posters & club activities',images:[]}]},
 {id:'girls-who-code',title:'Girls Who Code',kind:'Community',category:'Graphic / Visual Design',date:'August 2025 — present',status:'Outreach & Marketing Design Coordinator',summary:'STEM outreach & marketing design',description:'I help plan and coordinate STEM outreach events and collaborations for middle and high school students in the Albany region, and design marketing materials and social media content.',tools:['Visual design','Marketing','STEM outreach'],details:[],link:'https://girlswhocoderpi.github.io/',media:[]}
];
// Add verified artwork here. For 3D projects, use category: '3D Modeling',
// tools: ['Blender'], and separate media blocks for angles, process, wireframes and final renders.
export const artworks=[];
